### ISSUE TITLE
Support country code

### ISSUE THREAD

**Issue by neestell** [iflutter/intl_manager#5]
Hello
Is there a way to generate locale for a country? For example, `strings-en-rGB.xml` to `intl_en_rGB.arb` and `messages_en_rGB.dart`

Thank you

**Comment by shenkaige** [comment]
> Hello
> Is there a way to generate locale for a country? For example, `strings-en-rGB.xml` to `intl_en_rGB.arb` and `messages_en_rGB.dart`
> 
> Thank you

Hello, the problem has been solved. Please use git path to get the package.

For example:

```
intl_manager:
    git:
      url: https://github.com/iflutter/intl_manager
      ref: master
```
Thank you
